import random
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

random.seed(42)

CLINICS = [
    (1, "Harbour GP Clinic", "Pyrmont"),
    (2, "Westside Family Practice", "Parramatta"),
    (3, "Northshore Allied Health", "Chatswood"),
]
FIRST = ["Olivia", "Liam", "Mia", "Noah", "Aisha", "Jack", "Priya", "Lucas", "Mei", "Oliver",
         "Zara", "Ethan", "Chloe", "Arjun", "Ruby", "Leo", "Hannah", "Kai", "Isla", "Mateo"]
LAST = ["Nguyen", "Smith", "Patel", "Williams", "Chen", "Brown", "Singh", "Taylor", "Kim", "Wilson",
        "Martin", "Ali", "Jones", "Lee", "Kelly", "Ryan", "Walker", "Sharma", "White", "Thompson"]
REASONS = ["Repeat script", "Skin check", "Blood test review", "Flu vaccine", "Physio follow-up",
           "Mental health plan", "Care plan review", "Referral", "Sore knee", "Asthma review"]


def medicare() -> str:
    d = [random.randint(2, 6)] + [random.randint(0, 9) for _ in range(7)]
    weights = [1, 3, 7, 9, 1, 3, 7, 9]
    check = sum(a * b for a, b in zip(d, weights)) % 10
    issue = random.randint(1, 9)
    s = "".join(map(str, d + [check, issue]))
    return f"{s[:4]} {s[4:9]} {s[9]}"


def luhn_check_digit(body: str) -> int:
    total = 0
    for i, ch in enumerate(reversed(body)):
        n = int(ch)
        if i % 2 == 0:
            n *= 2
            if n > 9:
                n -= 9
        total += n
    return (10 - total % 10) % 10


def ihi() -> str:
    body = "800360" + "".join(str(random.randint(0, 9)) for _ in range(9))
    s = body + str(luhn_check_digit(body))
    return f"{s[:4]} {s[4:8]} {s[8:12]} {s[12:]}"


def phone() -> str:
    return f"04{random.randint(10, 99)} {random.randint(100, 999)} {random.randint(100, 999)}"


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


lines = ["-- Generated by scripts/generate_seed.py", ""]
for cid, name, suburb in CLINICS:
    lines.append(f"INSERT INTO clinics (id, name, suburb) VALUES ({cid}, {q(name)}, {q(suburb)});")
lines.append("")

base = datetime(2026, 10, 12, 9, 0, tzinfo=timezone.utc)
pid = 0
patient_rows, appt_rows, note_rows = [], [], []
for cid, _, _ in CLINICS:
    for _ in range(20):
        pid += 1
        fn, ln = random.choice(FIRST), random.choice(LAST)
        dob = date(1940, 1, 1) + timedelta(days=random.randint(0, 30000))
        mc, ih, ph = medicare(), ihi(), phone()
        email = f"{fn.lower()}.{ln.lower()}{pid}@example.com"
        patient_rows.append(
            f"({cid}, {q(fn + ' ' + ln)}, '{dob.isoformat()}', {q(mc)}, {q(ih)}, {q(ph)}, {q(email)})")
        for _ in range(3):
            when = base + timedelta(days=random.randint(0, 20), hours=random.randint(0, 7))
            appt_rows.append(f"({cid}, {pid}, '{when.isoformat()}', {q(random.choice(REASONS))})")
        note = random.choice([
            f"Pt called to confirm details. Medicare {mc} verified, best contact {ph}.",
            f"Reviewed bloods, all within range. Discussed diet and exercise.",
            f"Referral letter sent. IHI {ih} attached to eReferral.",
            f"Patient asked for results by email ({email}). Sent via secure portal instead.",
            f"Follow up in 6 weeks. No change to medication.",
        ])
        when = base - timedelta(days=random.randint(1, 200))
        note_rows.append(f"({cid}, {pid}, '{when.isoformat()}', {q(note)})")

lines.append("INSERT INTO patients (clinic_id, full_name, dob, medicare_number, ihi, phone, email) VALUES")
lines.append(",\n".join(patient_rows) + ";\n")
lines.append("INSERT INTO appointments (clinic_id, patient_id, starts_at, reason) VALUES")
lines.append(",\n".join(appt_rows) + ";\n")
lines.append("INSERT INTO clinical_notes (clinic_id, patient_id, created_at, note) VALUES")
lines.append(",\n".join(note_rows) + ";\n")

out = Path(__file__).resolve().parent.parent / "lab" / "db" / "init" / "02_seed.sql"
out.write_text("\n".join(lines))
print(f"wrote {out} ({pid} patients)")
